AWSTemplateFormatVersion: 2010-09-09
Description: 'Main Stack'

Parameters:
  SiteID:
    Type: String
    Description: "3-letter Site identifier"
  CFBucket:
    Type: String
    Description: "S3 bucket you will upload CloudFormation templates"
  Region:
    Type: String
    Default: 'ap-northeast-1'
    Description: "Region you will create stack"
  DomainName:
    Type: String
    Description: 'DomainName for this site'
#
# Parameters for subnet
#
  CidrVPC:
    Type: String
    Description: 'CIDR for VPC'
  CidrALL:
    Type: String
    Default: '172.31.0.0/23'
  CidrPubA:
    Type: String
    Default: '172.31.0.0/26'
  CidrPubC:
    Type: String
    Default: '172.31.0.64/26'
  CidrPubD:
    Type: String
    Default: '172.31.0.128/26'
  CidrPrvA:
    Type: String
    Default: '172.31.1.0/26'
  CidrPrvC:
    Type: String
    Default: '172.31.1.64/26'
  CidrPrvD:
    Type: String
    Default: '172.31.1.128/26'

#
# Parameters for Sub Stacks
#
  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ""
    Description: 'AMI-ID you wanna use to create instances'
  HostedZoneId:
    Type: String
    Default: "no"
    Description: 'HostedZoneId already created'
  MasterUsername:
    Type: String
    Default: ""
    Description: 'RDS Master User Name'
  MasterUserPassword:
    Type: String
    Default: ""
    Description: 'RDS Master User Password'
  PrimaryRegion:
    Type: String
    Default: "no"
    Description: 'Primary RDS site'
#
# Parameters for Conditions
#
  AMI:
    Type: String
    Default: 'no'
    AllowedValues: [ 'yes', 'no' ]
  R53:
    Type: String
    Default: 'no'
    AllowedValues: [ 'yes', 'no' ]
  S3:
    Type: String
    Default: 'no'
    AllowedValues: [ 'yes', 'no' ]
  RDS:
    Type: String
    Default: 'no'
    AllowedValues: [ 'yes', 'no' ]
  ECA:
    Type: String
    Default: 'no'
    AllowedValues: [ 'yes', 'no' ]
  EFS:
    Type: String
    Default: 'no'
    AllowedValues: [ 'yes', 'no' ]
  ASG:
    Type: String
    Default: 'no'
    AllowedValues: [ 'yes', 'no' ]
  CDN:
    Type: String
    Default: 'no'
    AllowedValues: [ 'yes', 'no' ]
  LMD:
    Type: String
    Default: 'no'
    AllowedValues: [ 'yes', 'no' ]
  IAM:
    Type: String
    Default: 'no'
    AllowedValues: [ 'yes', 'no' ]

#
# Conditions created when "yes"
#
Conditions:
  AMI:
    !Equals [ !Ref AMI, 'yes' ]
  R53:
    !Equals [ !Ref R53, 'yes' ]
  S3:
    !Equals [!Ref S3, 'yes']
  RDS:
    !Equals [!Ref RDS, 'yes']
  ECA:
    !Equals [!Ref ECA, 'yes']
  EFS:
    !Equals [!Ref EFS, 'yes']
  ASG:
    !Equals [!Ref ASG, 'yes']
  CDN:
    !Equals [!Ref CDN, 'yes']
  LMD:
    !Equals [!Ref LMD, 'yes']
  IAM:
    !Equals [!Ref IAM, 'yes']

Resources:
  # VPC: Virtual Private Cloud
  VPCres:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub "${CFBucket}/templates/_VPC.yaml"
      #TemplateURL: !Sub "${CFBucket}/templates/_VPCe.yaml"  # VPCエンドポイント
      Parameters:
        StackName: !Ref 'AWS::StackName'
        CidrVPC: !Ref CidrVPC
        CidrALL: !Ref CidrALL
        CidrPubA: !Ref CidrPubA
        CidrPubC: !Ref CidrPubC
        CidrPubD: !Ref CidrPubD
        CidrPrvA: !Ref CidrPrvA
        CidrPrvC: !Ref CidrPrvC
        CidrPrvD: !Ref CidrPrvD
  # AMI: Amazon Machine Interface
  AMIres:
    Type: 'AWS::CloudFormation::Stack'
    Condition: 'AMI'
    Properties:
      TemplateURL: !Sub "${CFBucket}/templates/_AMI.yaml"
      Parameters:
        StackName: !Ref 'AWS::StackName'
  # R53: Route53 hosted Zone
  R53res:
    Type: 'AWS::CloudFormation::Stack'
    Condition: 'R53'
    Properties:
      TemplateURL: !Sub "${CFBucket}/templates/_R53.yaml"
      Parameters:
        StackName: !Ref 'AWS::StackName'
        DomainName: !Ref DomainName  # ホストゾーンのドメイン名
  # S3: Simple Storage Service
  S3res:
    Type: 'AWS::CloudFormation::Stack'
    Condition: 'S3'
    Properties:
      TemplateURL: !Sub "${CFBucket}/templates/_S3.yaml"
      Parameters:
        StackName: !Ref 'AWS::StackName'
        BucketName: !Sub "${SiteID}.${Region}.${DomainName}"  # デプロイ物件が格納されるバケット

  # RDS: Relational Database System
  RDSres:
    Type: 'AWS::CloudFormation::Stack'
    Condition: 'RDS'
    Properties:
      TemplateURL: !Sub "${CFBucket}/templates/_RDS.yaml"
      Parameters:
        StackName: !Ref 'AWS::StackName'
        MasterUsername: !Ref MasterUsername          # DBの管理者ユーザ名
        MasterUserPassword: !Ref MasterUserPassword  # パスワード
        PrimaryRegion: !Ref PrimaryRegion            # CRRRをするときのプライマリノードが存在するリージョン
    DependsOn: VPCres

  # ECA: Elastic Cache
  ECAres:
    Type: 'AWS::CloudFormation::Stack'
    Condition: 'ECA'
    Properties:
      TemplateURL: !Sub "${CFBucket}/templates/_ECA.yaml"
      Parameters:
        StackName: !Ref 'AWS::StackName'
    DependsOn: VPCres

  # ASG: Auto Scaling Group
  ASGres:
    Type: 'AWS::CloudFormation::Stack'
    Condition: 'ASG'
    Properties:
      TemplateURL: !Sub "${CFBucket}/templates/_ASG.yaml"
      #TemplateURL: !Sub "${CFBucket}/templates/_ASGe.yaml"  #  VPCエンドポイント
      Parameters:
        StackName: !Ref 'AWS::StackName'
        ImageId: !Sub "${ImageId}"                            # EC2インスタンスのAMI
        HostName: !Sub "www.${DomainName}"                    # ALBに解決されるホスト名
        BucketName: !Sub "${SiteID}.${Region}.${DomainName}"  # デプロイ物件が格納されるバケット
        HostedZoneId: !Ref HostedZoneId                       # 既存のホストゾーンがある場合は、IDを受け取る。
    DependsOn: VPCres
